import os, json, re
from datetime import datetime
import pandas as pd

IN_SIGNALS = "signals_template.csv"
IN_RULES   = "category_rules.json"
IN_ICP     = "icp_profile.json"
OUT_DIR    = "out"
os.makedirs(OUT_DIR, exist_ok=True)

try:
    signals = pd.read_csv(IN_SIGNALS)
except Exception:
    signals = pd.read_csv(IN_SIGNALS, on_bad_lines="skip", engine="python")

with open(IN_RULES, "r", encoding="utf-8") as f: rules = json.load(f)
with open(IN_ICP, "r", encoding="utf-8") as f: icp = json.load(f)

def classify(text):
    text_l = str(text).lower()
    hits = []
    for cat, kws in rules.items():
        for kw in kws:
            if kw.lower() in text_l:
                hits.append(cat); break
    return "|".join(sorted(set(hits))) if hits else "Misc"

need_cols = {"date","source","title","url","snippet"}
missing = need_cols - set(signals.columns)
if missing:
    raise SystemExit(f"signals_template.csv is missing column(s): {sorted(missing)}")

signals["haystack"] = signals[["title","snippet","source"]].fillna("").agg(" ".join, axis=1)
signals["categories"] = signals["haystack"].apply(classify)
signals_out = os.path.join(OUT_DIR, "signals_classified.csv")
signals.drop(columns=["haystack"]).to_csv(signals_out, index=False)

rows = []
cats = set()
for c in signals["categories"]:
    for part in str(c).split("|"):
        if part.strip(): cats.add(part.strip())
for cat in sorted(cats):
    mask = signals["categories"].str.contains(rf"\b{re.escape(cat)}\b", na=False)
    rows.append({"category":cat, "count": int(mask.sum())})
bycat = pd.DataFrame(rows).sort_values("count", ascending=False)
bycat_out = os.path.join(OUT_DIR, "category_counts.csv")
bycat.to_csv(bycat_out, index=False)

def take(n, df): return df.head(n)[["date","title","source"]].to_dict(orient="records")
hints = {
    "Timing": "Plan campaigns around license/IPO milestones and big launches.",
    "Messaging": "Lean into trust, compliance, and global money movement narrative.",
    "ICP": "Target travelers, crypto-curious users, and SMB finance leads by region.",
    "Product": "Promote stablecoin zero-fee swaps, AI assistant, and LATAM expansion benefits.",
    "Partnerships": "Co-market with new regional partners/banks; local credibility.",
    "Funding": "Use profit/scale proof points in enterprise pitches.",
    "Hiring": "Prospect teams hiring payments/treasury roles.",
    "Regulatory/Risk": "Prepare objection handles on license status and account freezes.",
    "Geography": "Sequence outreach: France & LATAM momentum; UK pending."
}

md_path = os.path.join(OUT_DIR, "summary.md")
with open(md_path, "w", encoding="utf-8") as f:
    f.write(f"# GTM Intel Summary — {icp.get('company','Target')}\n\n")
    f.write("## Category Breakdown\n")
    for _, r in bycat.iterrows():
        f.write(f"- **{r['category']}**: {r['count']} signals\n")
    f.write("\n## Short Insights & GTM Recommendations\n")
    for cat in bycat["category"]:
        if cat == "Misc": continue
        top = signals[signals["categories"].str.contains(cat, na=False)].sort_values("date", ascending=False)
        if len(top)==0: continue
        f.write(f"\n### {cat}\n- GTM Hint: {hints.get(cat, 'Use momentum here for outreach.')}\n")
        for ex in take(3, top):
            f.write(f"  - {ex['date']} — {ex['title']} ({ex['source']})\n")
    f.write("\n---\nGenerated by GTM_Intel_Task2.py\n")

print("Done! Outputs in ./out/")
print("-", signals_out)
print("-", bycat_out)
print("-", md_path)
